Repository koderover/zadig-portal, pull requests merged in 2021-09, with the labels that each got.

#82 Add new loading page.
  package.json
  src/components/entry/loading.vue
  src/main.js
  yarn.lock
Labels: enhancement

#90 Fix variables undefined.
  src/components/entry/login.vue
Labels: bug

#97 Validate jira host's url.
  src/components/setting/integration/jira.vue
Labels: enhancement

#112 Order envs by name.
  src/components/projects/env/outer_env/home.vue
Labels: enhancement

#119 Fix typo
  src/components/projects/service_mgr/helm/components/helm/match_rule.vue
Labels: documentation, enhancement
