Repository koderover/zadig-portal, pull requests merged in 2022-11, with the labels that each got.

#1308 feat:optimize drop-down box for new branch entries.
  patches/element-ui+2.15.10.patch
  src/components/common/customWorkflowBuildRows.vue
  src/components/common/customWorkflowCommonRows.vue
  src/components/common/workflowBuildRows.vue
  src/components/projects/scanner/common/runScannerTask.vue
  src/mobile/project/workflow/product/common/workflowBuildRows.vue
Labels: enhancement

#1310 fix:add label to new branch entries.
  patches/element-ui+2.15.10.patch
  src/components/common/customWorkflowBuildRows.vue
  src/components/common/customWorkflowCommonRows.vue
  src/components/common/workflowBuildRows.vue
  src/components/projects/scanner/common/runScannerTask.vue
Labels: bug

#1311 feat:remove bootstrap dependency to reduce pkg size.
  src/assets/css/quote/bootstarp.less
  src/components/entry/login.vue
  src/components/entry/passwordLogin.vue
Labels: enhancement

#1295 feat: optimize job
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobFreestyle.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: enhancement

#1313 feat: add scanner job in custom workflow
  src/components/common/customWorkflowBuildRows.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/productCustomTaskDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/config.js
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: enhancement

#1317 feat:show type on git provider's namespace.
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
Labels: enhancement

#1316 fix: set the link to disable if the url doesn‘t exist.
  src/components/projects/scanner/create.vue
  src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
Labels: bug

#1319 feat:using local data when searching namespace from special provider.
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
Labels: enhancement

#1309 feat: don't request workflow detail api when other api get error.
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: enhancement

#1321 fix:fix commit link.
  src/components/projects/workflow/common/repoJump.vue
  src/components/projects/workflow/commonTaskDetail.vue
Labels: bug

#1325 fix:add label to repoOwner.
  src/components/projects/serviceMgr/common/serviceTree.vue
Labels: enhancement

#1326 fix:fix namespace is undefined.
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
Labels: bug

#1328 fix:fix redirect query is missing when token is expired.
  src/api/index.js
Labels: bug

#1327 fix: Chinese products in customer deliveries cannot be deleted
  src/components/entry/home/topbar.vue
Labels: bug

#1330 feat:optimize sidebar scrollbar style.
  src/assets/css/common/scroll-bar.less
  src/components/entry/home/sidebar.vue
Labels: enhancement

#1332 fix(style):right alignment of project’s buttons.
  src/components/projects/detail_ope/home.vue
Labels: enhancement

#1333 fix(typo):fix typo of app permission.
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/setting/integration/code.vue
Labels: documentation

#1335 fix:fix projectPermission is deleted.
  src/api/index.js
  src/store/index.js
  src/store/modules/projectPermission.js
  src/store/mutations.js
Labels: bug

#1338 feat(style):change style of topbar.
  src/components/entry/home/common/notification.vue
  src/components/entry/home/topbar.vue
Labels: enhancement

#1337 feat(ui):optimize workflow list.
  src/assets/css/theme/index.css
  src/common/cusTags.vue
  src/components/projects/workflow/list.vue
  src/components/projects/workflow/list/productRow.vue
  src/utilities/utilities.js
Labels: enhancement

#1339 fix(icon):fix project's loading icon.
  src/components/projects/detail_ope/detail.vue
Labels: enhancement

#1341 chore:document links as a component.
  src/components/entry/home/common/docLink.vue
  src/components/entry/home/topbar.vue
Labels: enhancement

#1343 feat(ux):optimize shortcut link component.
  src/assets/css/quote/iconfont.css
  src/assets/fonts/iconfont/iconfont.eot
  src/assets/fonts/iconfont/iconfont.ttf
  src/assets/fonts/iconfont/iconfont.woff
  src/assets/fonts/iconfont/iconfont.woff2
  src/assets/icons/font/iconfont.svg
  src/assets/icons/others/doc.svg
  src/assets/icons/others/link.svg
  src/components/entry/home.vue
  src/components/entry/home/common/docLink.vue
  src/components/entry/home/common/shortCutLink.vue
  src/components/entry/home/floatLink.vue
  src/components/entry/home/topbar.vue
Labels: enhancement

#1340 fix(workflow):fix custom workflow issues and clean code.
  src/components/projects/detail_ope/detail.vue
  src/components/projects/workflow/list/virtualListItem.vue
  src/components/projects/workflow/productCustomDetail.vue
  src/components/projects/workflow/productDetail.vue
Labels: bug

#1344 feat(ux):optimize workflow view component.
  src/api/index.js
  src/components/projects/workflow/list.vue
  src/components/projects/workflow/list/productRow.vue
Labels: enhancement

#1352 feat:import yamls from other git provider.
  src/api/index.js
  src/components/projects/common/importValues/index.vue
  src/components/projects/common/importValues/repository.vue
  src/components/projects/common/importValues/treeFile.vue
  src/components/projects/common/mixin/importRepo.js
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/templateLibrary/chart/importChart.vue
Labels: bug, enhancement

#1365 fix:fix codeSource is undefined.
  src/components/projects/common/mixin/importRepo.js
  src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
Labels: bug

#1367 fix:assign template data to init payload.
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
  src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
Labels: bug

#1375 fix:set project prop to current project by default.
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
Labels: bug

#1376 fix:don't check yaml in template lib.
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
Labels: bug

#1381 fix:fix step missing when run job.
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/commonTaskDetail/build.vue
Labels: bug

#1382 feat:change layout of integration.
  src/api/index.js
  src/components/projects/common/integrationRegistry.vue
  src/components/setting/cluster/manage.vue
  src/components/setting/integration/external.vue
  src/components/setting/integration/githubApp.vue
  src/components/setting/integration/home.vue
  src/components/setting/integration/project.vue
  src/components/setting/registry/manage.vue
Labels: enhancement

#1385 fix(link):fix smtp link url.
  src/components/entry/home.vue
Labels: bug

#1386 feat:add link to build name.
  src/components/templateLibrary/builds/fileAside.vue
Labels: enhancement

#1380 feat:repo supports bulk import.
  src/common/serviceRepoSelect.vue
  src/components/projects/build/zadigBuild.vue
Labels: enhancement

#1390 fix:fix valuesPath not show when edit service.
  src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
  src/components/projects/env/env_detail/components/chartList.vue
Labels: bug

#1394 feat:add checking to bulk import.
  src/common/serviceRepoSelect.vue
Labels: enhancement

#1397 feat:get namesapce data from cache when data is duplicate.
  src/common/serviceRepoSelect.vue
Labels: enhancement

#1401 fix:fix redirect's query is missing.
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/setting/integration/code.vue
Labels: bug

#1413 fix:fix gitRepoConfig is undefined.
  src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
Labels: enhancement

#1416 fix(style):fix workflow desc style.
  src/components/projects/workflow/list/workflowRow.vue
Labels: bug

#1415 fix(style):fix workflow desc style.
  src/components/projects/workflow/list/workflowRow.vue
Labels: bug

#1420 fix:fix permission tooltip.
  src/components/projects/serviceMgr/common/serviceTree.vue
Labels: bug

#1419 fix:fix permission tooltip.
  src/components/projects/serviceMgr/common/serviceTree.vue
Labels: bug

#1407 feat: support share storage between custom workflow jobs
  src/api/index.js
  src/assets/css/quote/iconfont.css
  src/components/projects/build/advancedConfig.vue
  src/components/projects/build/zadigBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/settings.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobFreestyle.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobPlugin.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/settings.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobFreestyle.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobPlugin.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobScanning.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobTest.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
  src/components/setting/cluster/manage.vue
  src/components/templateLibrary/workflows/components/base/settings.vue
  src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
  src/components/templateLibrary/workflows/components/jobs/jobFreestyle.vue
  src/components/templateLibrary/workflows/components/jobs/jobPlugin.vue
  src/components/templateLibrary/workflows/components/jobs/jobScanning.vue
  src/components/templateLibrary/workflows/components/jobs/jobTest.vue
  src/components/templateLibrary/workflows/config.vue
Labels: enhancement

#1418 cherry-pick 1407
  src/api/index.js
  src/assets/css/quote/iconfont.css
  src/components/projects/build/advancedConfig.vue
  src/components/projects/build/zadigBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/settings.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobFreestyle.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobPlugin.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobScanning.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobTest.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/settings.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobFreestyle.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobPlugin.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobScanning.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobTest.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
  src/components/setting/cluster/manage.vue
  src/components/templateLibrary/workflows/components/base/settings.vue
  src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
  src/components/templateLibrary/workflows/components/jobs/jobFreestyle.vue
  src/components/templateLibrary/workflows/components/jobs/jobPlugin.vue
  src/components/templateLibrary/workflows/components/jobs/jobScanning.vue
  src/components/templateLibrary/workflows/components/jobs/jobTest.vue
  src/components/templateLibrary/workflows/config.vue
Labels: enhancement

#1423 fix:fix displayName and service component issues.
  src/components/delivery/version/container/runWorkflow.vue
  src/components/delivery/version/k8s/detail.vue
  src/components/projects/workflow/productTaskDetail.vue
Labels: bug

#1425 fix(style):fix style of tag.
  src/components/projects/serviceMgr/common/serviceTree.vue
Labels: bug
