Repository koderover/zadig-portal, pull requests merged in 2022-03, with the labels that each got.

#317 feat(policy): custom cooperation
  src/api/index.js
  src/assets/css/quote/iconfont.css
  src/assets/fonts/iconfont.eot
  src/assets/fonts/iconfont.ttf
  src/assets/fonts/iconfont.woff
  src/assets/fonts/iconfont.woff2
  src/components/projects/detail_ope/components/initEnvDialog.vue
  src/components/projects/detail_ope/detail.vue
  src/components/projects/detail_ope/initialize.vue
  src/components/projects/env/createEnv.vue
  src/components/projects/env/createHelmEnv.vue
  src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
  src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
  src/components/projects/env/env_detail/components/recycleDialog.vue
  src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
  src/components/projects/env/env_detail/env_detail_comp.vue
  src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
  src/components/projects/env/k8sPmEnv/varList.vue
  src/components/projects/pipeline/workflow_common_detail.vue
  src/components/projects/pipeline/workflow_list.vue
  src/components/projects/pipeline/workflow_multi_detail.vue
  src/components/projects/policy/home.vue
  src/components/projects/policy/policy.vue
  src/components/projects/policy/policyDialog.vue
  src/components/projects/rbac/components/add-role-bind.vue
  src/components/projects/rbac/components/add-role.vue
  src/components/projects/rbac/components/look-over-policy.vue
  src/components/projects/rbac/home.vue
  src/components/projects/rbac/member.vue
  src/components/projects/rbac/policy.vue
  src/components/projects/rbac/role.vue
  src/router/index.js
Labels: enhancement

#608 feat:searching for users using remote method.
  src/components/projects/detail_ope/create.vue
  src/components/projects/rbac/addRoleBinding.vue
Labels: enhancement

#607 feat: support component and image name are inconsistent
  src/components/projects/detail_ope/components/cusDeliverable.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
  src/components/projects/serviceMgr/k8s/container/policy.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/workflow/common/k8sArtifactDeploy.vue
  src/components/projects/workflow/common/runWorkflow.vue
Labels: enhancement

#606 feat:support for creating environments through partial services
  src/api/index.js
  src/assets/css/component/service-mgr.less
  src/components/projects/common/imageItem.vue
  src/components/projects/env/env_detail/components/manageServicesDialog.vue
  src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/inner_env/createEnvDetail.vue
  src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/projects/workflow/common/k8sArtifactDeploy.vue
Labels: don't merge

#620 feat:move params from path to query.
  src/api/index.js
Labels: enhancement

#623 feat:remove service scaling restrictions.
  src/components/projects/env/inner_env/serviceDetail.vue
Labels: enhancement

#624 feat:use project aliases as filter conditions.
  src/components/insight/common/subTopbar.vue
Labels: enhancement

#638 feat:show payload in extension stage.
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/extension.vue
Labels: enhancement

#627 feat:support cache directory configuration.
  src/components/setting/cluster/manage.vue
Labels: enhancement

#639 fix:fix workflow's trigger shortcut.
  src/components/projects/workflow/list/virtualListItem.vue
Labels: bug

#644 fix:formatting service name.
  src/components/delivery/artifacts/detail.vue
  src/components/delivery/artifacts/index.vue
  src/components/projects/workflow/productTaskDetail/artifactDeploy.vue
Labels: bug

#646 feat:add tooltip to sidebar when it's closed.
  src/components/entry/home/sidebar.vue
Labels: enhancement

#648 feat:support search during branch selection.
  src/components/common/workflowBuildRows.vue
Labels: enhancement

#651 feat:change distribute stage to distribute deploy.
  src/components/projects/guide/pm/delivery.vue
  src/components/projects/workflow/productDetail.vue
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/distribute.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/sidebar.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/tab.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
  src/mobile/pipelines/detail.vue
  src/utilities/wordTranslate.js
Labels: enhancement

#663 fix:force environment update when adding services
  src/api/index.js
  src/components/projects/env/env_detail/components/manageServicesDialog.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug
