Repository koderover/zadig-portal, pull requests merged in 2022-05, with the labels that each got.

#813 fix:show checkbox when jenkins is disabled.
  src/components/projects/build/commonBuild.vue
Labels: bug

#814 fix:set select to disable when jenkins is't available.
  src/components/projects/build/commonBuild.vue
Labels: bug

#792 feat: service auto update
  src/api/index.js
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/templateLibrary/chart/index.vue
  src/components/templateLibrary/k8s/fileEditor.vue
  src/store/index.js
  src/store/modules/k8sService.js
  src/store/mutations.js
Labels: enhancement

#819 feat: service auto deploy
  src/components/projects/serviceMgr/k8s/container/policy.vue
Labels: enhancement

#822 feat:optimize variable editor.
  src/api/index.js
  src/common/variableEditor.vue
  src/common/variablePreviewEditor.vue
  src/components/projects/env/env_detail/components/manageK8sServicesDialog.vue
  src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: enhancement

#825 fix: button position and tootip and api
  src/api/index.js
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/templateLibrary/chart/aside/variableList.vue
  src/components/templateLibrary/chart/index.vue
Labels: bug

#827 fix: tips
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/templateLibrary/chart/aside/variableList.vue
Labels: bug

#820 feat: remove codehub
  src/components/setting/integration/code.vue
Labels: enhancement

#828 fix:fix error style in editor.
  src/common/variablePreviewEditor.vue
Labels: bug

#829 fix:fix errors undefined.
  src/common/variablePreviewEditor.vue
Labels: bug

#826 feat: code filter
  src/api/index.js
  src/components/projects/workflow/common/runWorkflow.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/buildDeploy.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
Labels: enhancement

#831 feat: helm environment can select chart names
  src/api/index.js
  src/assets/css/component/env-detail.less
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/components/serviceList.vue
  src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/workflow/productTaskDetail/filterStatus.vue
Labels: enhancement

#832 fix: create rollbackable k8s environments
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
Labels: bug

#833 fix: reset dialog
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
  src/store/modules/k8sService.js
Labels: bug

#837 feat:add variable editor to k8s env creation.
  src/components/projects/env/k8sPmEnv/varList.vue
Labels: enhancement

#839 fix:add variable preview editor to env creation
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
Labels: bug

#842 fix:get release info from task detail.
  src/components/projects/workflow/productTaskDetail.vue
Labels: bug

#845 fix:set default value when source_detail undefined.
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
Labels: bug

#847 fix(permission):add query 'projectName' to API.
  src/api/index.js
  src/components/projects/build/otherSteps.vue
  src/components/projects/build/zadigBuild.vue
  src/components/templateLibrary/builds/otherSteps.vue
Labels: bug

#848 cherry-pick:#841
  src/api/index.js
  src/components/projects/build/otherSteps.vue
  src/components/projects/build/zadigBuild.vue
  src/components/templateLibrary/builds/otherSteps.vue
Labels: bug

#838 feat: support standard git
  src/assets/css/common/build-row.less
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/common/workflowBuildRows.vue
  src/components/projects/build/envVariable.vue
  src/components/projects/common/mixin/importRepo.js
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/projects/serviceMgr/k8s/container/policy.vue
  src/components/projects/workflow/common/repoJump.vue
  src/components/projects/workflow/common/runWorkflow.vue
  src/components/setting/integration/code.vue
Labels: enhancement

#851 feat:permission enhancement.
  src/api/index.js
  src/components/delivery/common/subTopbar.vue
  src/components/delivery/version/index.vue
  src/components/entry/home.vue
  src/components/entry/home/sidebar.vue
  src/components/entry/home/subTopbar.vue
  src/components/projects/common/hosting/serviceBuild.vue
  src/components/projects/common/hosting/serviceModules.vue
  src/components/projects/detail_ope/detail.vue
  src/components/projects/detail_ope/home.vue
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/code.vue
  src/components/projects/serviceMgr/helm/components/editor/folder.vue
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/workflow/common/k8sArtifactDeploy.vue
  src/components/setting/users/manage.vue
  src/directive/permission/hasPermi.js
  src/main.js
  src/mixin/permissionMixin.js
  src/store/index.js
  src/store/modules/globalPermission.js
  src/store/modules/projectPermission.js
  src/store/mutations.js
  src/utilities/checkPermission.js
Labels: enhancement

#864 fix: code scan edit status is wrong
  src/components/projects/scanner/common/advancedConfig.vue
Labels: bug

#853 feat: repos support to import from gitee
  src/api/index.js
  src/components/common/gitFileTree.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitFileTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/templateLibrary/chart/importChart.vue
Labels: enhancement

#868 feat: alias
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/setting/integration/code.vue
Labels: enhancement

#870 fix:fix permission bugs
  src/api/index.js
  src/assets/css/common/common.less
  src/components/delivery/version/helm/detail.vue
  src/components/delivery/version/index.vue
  src/components/delivery/version/k8s/detail.vue
  src/components/entry/home/subTopbar.vue
  src/components/projects/build/config.vue
  src/components/projects/common/hosting/serviceModules.vue
  src/components/projects/common/pm/pmConfig.vue
  src/components/projects/common/pm/serviceList.vue
  src/components/projects/common/taskList.vue
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/components/serviceList.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/inner_env/pmServiceDetail.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/rbac/addRole.vue
  src/components/projects/scanner/common/runScannerTask.vue
  src/components/projects/scanner/common/scannerRow.vue
  src/components/projects/scanner/common/taskDetailScanner.vue
  src/components/projects/scanner/create.vue
  src/components/projects/scanner/history.vue
  src/components/projects/scanner/taskDetail.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/code.vue
  src/components/projects/serviceMgr/helm/components/editor/folder.vue
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/servicePm.vue
  src/components/projects/test/common/function/container/testRow.vue
  src/components/projects/test/common/function/functionTaskDetail.vue
  src/components/projects/workflow/commonDetail.vue
  src/components/projects/workflow/commonTaskDetail.vue
  src/components/projects/workflow/list/virtualListItem.vue
  src/components/projects/workflow/productDetail.vue
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/status/container/scannerStatus.vue
  src/components/setting/users/editUserInfo.vue
  src/components/templateLibrary/builds/fileEditor.vue
  src/components/templateLibrary/builds/fileTree.vue
  src/components/templateLibrary/builds/index.vue
  src/components/templateLibrary/chart/aside/variableList.vue
  src/components/templateLibrary/chart/folder.vue
  src/components/templateLibrary/chart/index.vue
  src/components/templateLibrary/dockerfile/fileEditor.vue
  src/components/templateLibrary/dockerfile/fileTree.vue
  src/components/templateLibrary/dockerfile/index.vue
  src/components/templateLibrary/k8s/fileEditor.vue
  src/components/templateLibrary/k8s/fileTree.vue
  src/components/templateLibrary/k8s/index.vue
  src/directive/index.js
  src/directive/permission/hasPermi.js
  src/utilities/checkPermission.js
Labels: bug

#872 fix: add alias
  src/components/projects/common/importValues/repository.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/setting/integration/code.vue
Labels: bug, enhancement

#876 fix: build error
  src/components/projects/serviceMgr/k8s/serviceAside.vue
Labels: bug

#877 fix:fix permission in create env btn.
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#776 feat: UI
  src/App.vue
  src/assets/css/common/helper.less
  src/assets/css/theme/index.css
  src/components/projects/build/advancedConfig.vue
  src/components/projects/detail_ope/home.vue
  src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
  src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
  src/components/projects/serviceMgr/helm/components/common/chartRepo.vue
  src/components/projects/serviceMgr/k8s/container/policy.vue
  src/components/projects/test/common/function/container/advancedConfig.vue
  src/components/projects/workflow/commonTaskDetail.vue
  src/components/setting/integration/code.vue
  src/components/setting/integration/githubApp.vue
  src/components/setting/integration/jira.vue
Labels: enhancement

#883 fix: ui
  src/components/projects/scanner/common/advancedConfig.vue
  src/components/setting/integration/account.vue
  src/components/setting/integration/code.vue
  src/components/setting/integration/githubApp.vue
  src/components/setting/integration/jira.vue
Labels: enhancement

#852 feat: git enhancement
  src/api/index.js
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/common/gitFileTree.vue
  src/components/common/testTrigger.vue
  src/components/common/workflowBuildRows.vue
  src/components/projects/common/importValues/index.vue
  src/components/projects/common/importValues/repository.vue
  src/components/projects/common/importValues/treeFile.vue
  src/components/projects/common/mixin/importRepo.js
  src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
  src/components/projects/env/env_detail/common/updateHelmEnvVariable.vue
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/components/updateHelmVarDialog.vue
  src/components/projects/env/env_detail/runWorkflow.vue
  src/components/projects/scanner/common/runScannerTask.vue
  src/components/projects/scanner/create.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitFileTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/projects/workflow/common/runCommonWorkflow.vue
  src/components/projects/workflow/common/runWorkflow.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/buildOperate.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
  src/components/templateLibrary/chart/importChart.vue
  src/components/templateLibrary/chart/index.vue
  src/mobile/pipelines/runWorkflow.vue
Labels: enhancement

#881 feat: support standard git enhancement
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/projects/common/importValues/repository.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/setting/integration/code.vue
Labels: enhancement

#892 fix:fix permission checking bug.
  src/directive/permission/hasPermi.js
  src/store/modules/globalPermission.js
  src/store/modules/projectPermission.js
  src/utilities/checkPermission.js
Labels: bug

#891 fix: repo_namespace
  src/common/repoSelect.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#893 fix: repo_namespace
  src/common/repoSelect.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#895 fix: notify and validate
  src/common/serviceRepoSelect.vue
  src/components/projects/build/zadigBuild.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue
Labels: bug

#900 fix: namespace
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
Labels: bug

#901 fix: namespace
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
Labels: bug

#904 fix:fix error response when delete service.
  src/api/index.js
  src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
Labels: bug

#907 fix: bug and ui
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/projects/build/commonBuild.vue
  src/components/projects/common/hosting/serviceBuild.vue
  src/components/projects/common/importValues/index.vue
  src/components/projects/guide/helm/runtime.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
Labels: bug

#909 fix:fix permission actions.
  src/components/projects/build/configDetail.vue
Labels: bug

#913 fix:fix permission in test row.
  src/components/projects/test/common/function/container/testRow.vue
Labels: bug

#922 fix:fix projectName missing in API.
  src/api/index.js
  src/components/projects/scanner/common/runScannerTask.vue
Labels: bug

#925 fix: build bug
  src/common/serviceRepoSelect.vue
  src/components/projects/build/zadigBuild.vue
Labels: bug

#933 fix: valuesData
  src/components/projects/guide/helm/runtime.vue
Labels: bug

#935 feat: hide Dind
  src/components/setting/cluster/manage.vue
Labels: enhancement

#936 feat: hide Dind
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/setting/cluster/manage.vue
Labels: enhancement
