Repository koderover/zadig-portal, pull requests merged in 2022-12, with the labels that each got.

#1429 fix:check target_tag when run custom workflow
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue
Labels: bug

#1439 fix(typo):fix typo.
  src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue
Labels: enhancement

#1442 fix(style):fix style of policy dialog.
  src/components/projects/policy/policy.vue
  src/components/projects/policy/policyDialog.vue
Labels: enhancement

#1447 feat:Add newline to the end of the ssh key.
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/setting/integration/code.vue
Labels: enhancement

#1449 feat: sonar support for using custom build images
  src/components/entry/home/sidebar.vue
  src/components/projects/scanner/create.vue
  src/components/setting/imgs/manage.vue
  src/router/index.js
Labels: enhancement

#1450 feat: the service displays an error message
  src/assets/css/component/env-detail.less
  src/components/projects/env/env_detail/components/serviceList.vue
Labels: enhancement

#1411 feat:support modify mailbox.
  src/api/index.js
  src/components/profile/manage.vue
Labels: enhancement

#1446 feat:add vue-i18n and language switcher.
  package.json
  src/common/langSwitcher.vue
  src/components/entry/home/topbar.vue
  src/components/entry/login.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/main.js
  yarn.lock
Labels: enhancement

#1457 translation:add translation to sign in and sign up.
  src/components/entry/components/forgetPassword.vue
  src/components/entry/components/signUp.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1458 translation:add translation to projects.
  src/components/projects/detail_ope/components/deleteProject.vue
  src/components/projects/detail_ope/home.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1459 translation:fix translation.
  src/lang/en.js
Labels: translation

#1460 transaltion:add translation to audit log.
  src/components/setting/auditlog/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1461 translation:add transaltion to announcement.
  src/components/setting/announcement/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1462 translation:add transaltion to packages.
  src/components/setting/apps/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1463 translation:add translation to images.
  src/components/setting/imgs/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1464 translation:add translation to helm repo.
  src/components/setting/helm/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1466 translation:add transaltion to subTopbar menu.
  src/components/entry/home/subTopbar.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1468 feat:provider aws supports 'region' prop.
  src/components/setting/storage/manage.vue
Labels: enhancement

#1469 feat:aws supports region prop.
  src/components/setting/storage/manage.vue
Labels: enhancement

#1471 translation:add translation to status.
  src/components/projects/workflow/status/container/customWorkflowStatus.vue
  src/components/projects/workflow/status/container/productWorkflowStatus.vue
  src/components/projects/workflow/status/container/scannerStatus.vue
  src/components/projects/workflow/status/container/testStatus.vue
  src/components/projects/workflow/status/status.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1467 feat: theme
  src/App.vue
  src/api/index.js
  src/assets/theme/index.less
  src/common/terminal.vue
  src/common/xtermDebug.vue
  src/common/xtermLog.vue
  src/common/xtermLogContainer.vue
  src/components/entry/home.vue
  src/components/entry/home/sidebar.vue
  src/components/profile/common/xterm.vue
  src/components/profile/home.vue
  src/components/profile/info.vue
  src/components/profile/preference.vue
  src/components/projects/detail_ope/view.vue
  src/components/projects/env/env_detail/common/pmXtermDebug.vue
  src/components/projects/env/k8sPmEnv/k8sServiceList.vue
  src/components/projects/env/pmEnv/createPmEnv.vue
  src/mobile/project/env/common/mobileContainerLog.vue
  src/router/index.js
  src/store/index.js
  src/store/modules/login.js
  src/store/modules/theme.js
  src/store/mutations.js
Labels: enhancement

#1474 translation:add global translation.
  src/components/projects/detail_ope/initialize.vue
  src/components/projects/env/env_detail/components/shareEnvDialog.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/workflow/productTaskDetail/filterStatus.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/confirmJobDialog.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/confirmJobDialog.vue
  src/components/setting/config/link.vue
  src/components/setting/integration/home.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1472 fix: approval list api add projectName
  src/api/index.js
  src/components/profile/info.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
  src/components/templateLibrary/workflows/components/stageOperate.vue
  src/components/templateLibrary/workflows/config.vue
Labels: bug

#1478 fix(typo):fix typo.
  src/components/setting/integration/components/addJenkins.vue
  src/components/setting/integration/components/configManage.vue
  src/components/setting/integration/components/sonarOperate.vue
  src/components/setting/integration/configManage.vue
  src/components/setting/integration/jenkins.vue
  src/components/setting/integration/sonar.vue
Labels: bug, typo

#1477 translation: testing
  src/components/common/testTrigger.vue
  src/components/projects/test/common/function/container/advancedConfig.vue
  src/components/projects/test/common/function/container/taskDetailTest.vue
  src/components/projects/test/common/function/container/testRow.vue
  src/components/projects/test/common/function/function.vue
  src/components/projects/test/common/function/functionDetail.vue
  src/components/projects/test/common/function/functionSummary.vue
  src/components/projects/test/common/function/functionTaskDetail.vue
  src/components/projects/test/common/functionTestCase.vue
  src/components/projects/test/common/functionTestSummary.vue
  src/components/projects/test/common/report/testCase.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1484 translation: code scanning
  src/components/common/customWorkflowBuildRows.vue
  src/components/common/customWorkflowCommonRows.vue
  src/components/common/workflowBuildRows.vue
  src/components/common/workflowTestRows.vue
  src/components/entry/home/subTopbar.vue
  src/components/projects/detail_ope/components/deleteProject.vue
  src/components/projects/scanner/common/advancedConfig.vue
  src/components/projects/scanner/common/runScannerTask.vue
  src/components/projects/scanner/common/scannerRow.vue
  src/components/projects/scanner/common/taskDetailScanner.vue
  src/components/projects/scanner/common/taskList.vue
  src/components/projects/scanner/create.vue
  src/components/projects/scanner/history.vue
  src/components/projects/scanner/home.vue
  src/components/projects/scanner/taskDetail.vue
  src/components/projects/test/common/function/functionTaskDetail.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/mobile/project/workflow/product/common/workflowBuildRows.vue
  src/mobile/project/workflow/product/common/workflowTestRows.vue
Labels: translation

#1488 translation:add translation to env creation.
  src/common/variablePreviewEditor.vue
  src/components/projects/common/importConfig/index.vue
  src/components/projects/common/importValues/index.vue
  src/components/projects/env/env_detail/common/envConfig.vue
  src/components/projects/env/env_detail/envConfig/home.vue
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/env/k8sPmEnv/k8sServiceList.vue
  src/components/projects/env/k8sPmEnv/varList.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1489 translation:add transaltion to loading.
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/env/pmEnv/createPmEnv.vue
Labels: translation

#1491 translation:add translation to helm and hosing env creation.
  src/components/projects/common/hosting/addHostEnv.vue
  src/components/projects/common/importValues/keyValue.vue
  src/components/projects/env/env_detail/common/updateHelmEnvChart.vue
  src/components/projects/env/env_detail/components/updateHelmEnvTemp.vue
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/hostEnv/createHostEnv.vue
  src/components/projects/env/hostEnv/editExternalConfig.vue
  src/components/projects/env/hostEnv/editHostService.vue
  src/components/projects/env/pmEnv/createPmEnv.vue
  src/components/projects/serviceMgr/common/checkResource.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1495 translation:add translation to global.
  src/components/delivery/version/index.vue
  src/components/profile/common/helpLink.vue
  src/components/setting/plugins/manage.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1497 translation:add translation to env configuration.
  src/components/delivery/artifacts/detail.vue
  src/components/projects/env/env_detail/components/serviceList.vue
  src/components/projects/env/env_detail/envConfig/commonConfig.vue
  src/components/projects/env/env_detail/envConfig/home.vue
  src/components/projects/env/env_detail/envConfig/versionHistory.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/guide/helm/delivery.vue
  src/components/projects/guide/k8s/delivery.vue
  src/components/projects/guide/pm/delivery.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1499 translation:add transaltion to onboarding.
  src/components/projects/common/hosting/runWorkflow.vue
  src/components/projects/env/hostEnv/editExternalConfig.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/guide/common/step.vue
  src/components/projects/guide/helm/basicInfo.vue
  src/components/projects/guide/helm/delivery.vue
  src/components/projects/guide/helm/runtime.vue
  src/components/projects/guide/helm/service.vue
  src/components/projects/guide/host/components/step.vue
  src/components/projects/guide/host/hostConfig.vue
  src/components/projects/guide/k8s/basicInfo.vue
  src/components/projects/guide/k8s/createEnv.vue
  src/components/projects/guide/k8s/delivery.vue
  src/components/projects/guide/k8s/runtime.vue
  src/components/projects/guide/k8s/service.vue
  src/components/projects/guide/pm/config.vue
  src/components/projects/guide/pm/delivery.vue
  src/components/projects/guide/pm/deploy.vue
  src/components/projects/guide/pm/info.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1501 translation:add transaltion to project rbac.
  src/components/projects/rbac/addRole.vue
  src/components/projects/rbac/addRoleBinding.vue
  src/components/projects/rbac/home.vue
  src/components/projects/rbac/member.vue
  src/components/projects/rbac/policy.vue
  src/components/projects/rbac/role.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: translation

#1504 fix:fix the style issue of en mode and add some translation.
  src/assets/css/component/file-editor.less
  src/assets/css/component/service-help.less
  src/common/host/manageHost.vue
  src/components/delivery/version/helm/createVersion/config.vue
  src/components/projects/build/advancedConfig.vue
  src/components/projects/common/hosting/serviceModules.vue
  src/components/projects/common/importValues/repository.vue
  src/components/projects/common/importValues/varGroups.vue
  src/components/projects/common/pm/pmConfig.vue
  src/components/projects/detail_ope/components/cusDeliverable.vue
  src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
  src/components/projects/env/env_detail/components/manageK8sServicesDialog.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/group/index.vue
  src/components/projects/policy/policyDialog.vue
  src/components/projects/serviceMgr/common/importFromNamespace.vue
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/code.vue
  src/components/projects/serviceMgr/helm/components/common/chartRepo.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue
  src/components/projects/serviceMgr/helm/components/editor/order.vue
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceHost.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/projects/serviceMgr/servicePm.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobK8sResourceUpdate.vue
  src/components/setting/cluster/manage.vue
  src/components/setting/integration/account.vue
  src/components/setting/plugins/manage.vue
  src/components/setting/registry/manage.vue
  src/components/setting/storage/manage.vue
  src/components/templateLibrary/builds/fileAside.vue
  src/components/templateLibrary/dockerfile/fileAside.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/workflows/components/jobs/jobK8sResourceUpdate.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug, translation

#1486 feat: notify add created type
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/config.js
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/config.js
  src/components/templateLibrary/workflows/config.js
Labels: enhancement

#1507 fix: ui
  src/assets/css/theme/index.css
Labels: bug

#1506 fix: ui
  src/components/projects/detail_ope/home.vue
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
  src/components/projects/workflow/common/k8sArtifactDeploy.vue
  src/components/projects/workflow/common/runWorkflow.vue
Labels: bug

#1508 translation:add translation to delivery center.
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/common/artifactDownload.vue
  src/components/delivery/artifacts/detail.vue
  src/components/delivery/artifacts/index.vue
  src/components/delivery/common/subTopbar.vue
  src/components/delivery/version/helm/createVersion.vue
  src/components/delivery/version/helm/detail.vue
  src/components/delivery/version/index.vue
  src/components/delivery/version/k8s/detail.vue
  src/components/projects/env/inner_env/pmServiceDetail.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/mobile/project/detail.vue
  src/mobile/project/env/envDetail.vue
  src/mobile/project/env/helmServiceDetail.vue
  src/mobile/project/env/k8sServiceDetail.vue
  src/mobile/project/workflow/product/detail.vue
Labels: translation

#1505 translation:templates and builds
  src/components/insight/service/deploy.vue
  src/components/insight/service/deploySummary.vue
  src/components/insight/service/health.vue
  src/components/insight/service/view.vue
  src/components/projects/build/advancedConfig.vue
  src/components/projects/build/buildEnv.vue
  src/components/projects/build/commonBuild.vue
  src/components/projects/build/config.vue
  src/components/projects/build/configDetail.vue
  src/components/projects/build/envVariable.vue
  src/components/projects/build/jenkinsBuild.vue
  src/components/projects/build/otherSteps.vue
  src/components/projects/build/zadigBuild.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobImageDistribute.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobImageDistribute.vue
  src/components/statistics/common/barChart.vue
  src/components/templateLibrary/builds/advancedConfig.vue
  src/components/templateLibrary/builds/buildEnv.vue
  src/components/templateLibrary/builds/envVariable.vue
  src/components/templateLibrary/builds/fileAside.vue
  src/components/templateLibrary/builds/fileTree.vue
  src/components/templateLibrary/builds/index.vue
  src/components/templateLibrary/builds/otherSteps.vue
  src/components/templateLibrary/builds/zadigBuild.vue
  src/components/templateLibrary/chart/aside.vue
  src/components/templateLibrary/chart/aside/referenceList.vue
  src/components/templateLibrary/chart/aside/variableList.vue
  src/components/templateLibrary/chart/folder.vue
  src/components/templateLibrary/chart/importChart.vue
  src/components/templateLibrary/chart/index.vue
  src/components/templateLibrary/common/subTopbar.vue
  src/components/templateLibrary/dockerfile/fileAside.vue
  src/components/templateLibrary/dockerfile/fileEditor.vue
  src/components/templateLibrary/dockerfile/fileTree.vue
  src/components/templateLibrary/dockerfile/index.vue
  src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
  src/components/templateLibrary/workflows/components/jobs/jobImageDistribute.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/mobile/project/workflow/product/common/runCustomWorkflow.vue
Labels: translation

#1487 feat:optimize variable editor in service.
  src/api/index.js
  src/assets/css/quote/iconfont.css
  src/assets/fonts/iconfont/iconfont.eot
  src/assets/fonts/iconfont/iconfont.ttf
  src/assets/fonts/iconfont/iconfont.woff
  src/assets/fonts/iconfont/iconfont.woff2
  src/assets/icons/font/iconfont.svg
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/k8s/index.vue
Labels: enhancement

#1519 fix:fix $t is undefined.
  src/components/projects/policy/policyDialog.vue
Labels: bug

#1521 fix:fix typo
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug

#1516 feat(style):change style of workflow list.
  src/components/projects/workflow/list/workflowRow.vue
Labels: enhancement

#1524 fix:fix i18n.
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug

#1525 fix(style):fix style of tooltip.
  src/assets/css/common/colorEnum.less
  src/common/host/manageHost.vue
  src/components/delivery/common/subTopbar.vue
  src/components/entry/home/sidebar.vue
  src/components/entry/home/subTopbar.vue
  src/components/projects/workflow/list/workflowRow.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug

#1526 fix:fix i18n key.
  src/components/projects/workflow/workflowEditor/customWorkflow/config.js
Labels: bug

#1527 fix:fix i18n key.
  src/components/projects/workflow/workflowEditor/customWorkflow/config.js
Labels: bug

#1528 tooltip:add tooltip.
  src/components/setting/integration/home.vue
  src/components/setting/users/components/roleOperate.vue
Labels: bug

#1531 fix: modify disabled color
  src/assets/css/common/common.less
Labels: bug

#1539 fix: minor bugs
  src/components/common/testTrigger.vue
  src/components/projects/common/importValues/repository.vue
  src/components/projects/workflow/common/repoJump.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/lang/zh-CN.js
Labels: bug

#1538 fix: minor bugs
  src/components/common/testTrigger.vue
  src/components/projects/workflow/common/repoJump.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/jobs/jobBuild.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stageOperate.vue
  src/components/templateLibrary/workflows/components/jobs/jobBuild.vue
  src/components/templateLibrary/workflows/components/stageOperate.vue
  src/lang/zh-CN.js
Labels: bug

#1540 fix:checking ssh key before add new line.
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/setting/integration/code.vue
Labels: bug

#1541 fix:checking ssh key before add new line.
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/setting/integration/code.vue
Labels: bug

#1537 fix:fix minor bugs.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/k8s/fileEditor.vue
Labels: bug

#1543 fix:fix minor bugs in variables.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/k8s/fileEditor.vue
Labels: bug

#1546 fix:fix typo.
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug

#1550 fix:fix typo.
  src/components/projects/rbac/member.vue
Labels: bug

#1551 fix:fix typo.
  src/components/projects/rbac/member.vue
Labels: bug

#1552 fix:fix i18n key.
  src/lang/zh-CN.js
Labels: bug

#1553 fix:fix i18n key.
  src/lang/zh-CN.js
Labels: bug

#1555 fix:fix redirect when edit webhook.
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: bug

#1557 fix: minor bugs
  src/common/testTimer.vue
  src/components/projects/dashboard.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/productCustomDetail.vue
  src/components/projects/workflow/productDetail.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
Labels: bug

#1556 fix: minor bugs
  src/common/testTimer.vue
  src/components/projects/dashboard.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/productCustomDetail.vue
  src/components/projects/workflow/productDetail.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/components/stageOperate.vue
  src/components/projects/workflow/workflowEditor/releaseWorkflow/index.vue
  src/components/templateLibrary/workflows/components/stageOperate.vue
Labels: bug

#1558 fix:fix i18n key.
  src/components/setting/integration/code.vue
Labels: bug

#1559 fix:fix i18n key.
  src/components/setting/integration/code.vue
Labels: bug

#1560 fix(style):change dialog width.
  src/components/projects/workflow/list.vue
Labels: bug

#1561 fix(style):change dialog width.
  src/components/projects/workflow/list.vue
Labels: bug

#1563 fix:fix data update in slot.
  src/components/templateLibrary/k8s/fileAside.vue
Labels: bug

#1562 fix: repo attribute's label
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
Labels: bug

#1565 fix:fix data update in slot.
  src/components/templateLibrary/k8s/fileAside.vue
Labels: bug

#1566 fix:fix codehost id is undefined.
  src/components/templateLibrary/chart/importChart.vue
Labels: bug

#1567 fix:fix codehost id is undefined.
  src/components/templateLibrary/chart/importChart.vue
Labels: bug

#1570 fix:disable edit when service is shared service.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
Labels: bug

#1571 fix:disable edit when service is shared service.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
Labels: bug

#1576 fix:fix variable not update.
  src/components/templateLibrary/k8s/fileAside.vue
Labels: bug

#1577 fix:fix variable not update.
  src/components/templateLibrary/k8s/fileAside.vue
Labels: bug

#1588 fix:fix jsyaml load error.
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
Labels: bug

#1598 fix:get varibale_yaml from other prop.
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#1601 fix:fix upgrade env.
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#1605 fix:fix boolean not show.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/templateLibrary/k8s/fileAside.vue
Labels: bug

#1608 fix:update service list after save variables.
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#1610 fix:clean origin namespace when change provider.
  src/components/projects/common/mixin/importRepo.js
Labels: bug

#1620 fix:fix minor bugs.
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/k8s/index.vue
Labels: bug
