Repository koderover/zadig-portal, pull requests merged in 2022-04, with the labels that each got.

#671 feat:supports response info display in extension stage.
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/extension.vue
Labels: enhancement

#675 fix:show headers in extension request.
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/extension.vue
Labels: enhancement

#677 fix: fix response's data desc undefined.
  src/api/index.js
Labels: bug

#678 feat:modify test results download API.
  src/components/common/artifactDownload.vue
Labels: enhancement

#673 feat:supports gitee in providers.
  src/common/repoSelect.vue
  src/components/projects/test/common/function/container/taskDetailTest.vue
  src/components/projects/workflow/common/repoJump.vue
  src/components/setting/integration/code.vue
Labels: enhancement

#681 fix(style):change style of file table.
  src/components/common/artifactDownload.vue
Labels: bug

#684 fix:fix route query redirect in service.
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
Labels: bug

#679 feat:supports uploading files to object storage.
  src/components/projects/build/otherSteps.vue
Labels: enhancement

#660 feat:support the creation of shared environments
  src/api/index.js
  src/assets/css/component/env-detail.less
  src/components/projects/env/createHelmEnv.vue
  src/components/projects/env/env_detail/components/shareEnvDialog.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/k8sPmEnv/createK8sPmEnv.vue
Labels: enhancement

#691 fix:add doc link to ref.
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#693 fix:fix serviceName in jenkins build.
  src/components/common/workflowBuildRows.vue
  src/components/projects/workflow/productTaskDetail.vue
Labels: bug

#696 fix:fix autoSync undefined.
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
Labels: bug

#697 fix:fix autoSync undefined.
  src/components/projects/serviceMgr/helm/components/common/templateRepo.vue
Labels: bug

#702 fix:set scope to required and remove autocompletion
  src/components/setting/integration/account.vue
Labels: enhancement

#699 fix: env validate error
  src/components/projects/build/envVariable.vue
Labels: bug

#700 fix: env validate error
  src/components/projects/build/envVariable.vue
Labels: bug

#706 fix:checking status after enable share env.
  src/components/projects/env/env_detail/components/shareEnvDialog.vue
Labels: bug

#708 feat:add envType to tab's tooltip.
  src/common/chromeTabs.vue
Labels: enhancement

#680 feat:changing environment related API route.
  src/api/index.js
  src/common/xtermDebug.vue
  src/components/projects/env/inner_env/serviceDetail.vue
Labels: enhancement

#703 feat:supports retag image in helm version.
  src/api/index.js
  src/components/delivery/version/helm/createVersion.vue
  src/components/delivery/version/helm/createVersion/push.vue
Labels: enhancement

#710 feat:breadcrumb supports show project alias.
  src/components/delivery/version/detail.vue
  src/components/delivery/version/index.vue
  src/components/entry/home/topbar.vue
  src/components/projects/build/config.vue
  src/components/projects/build/configDetail.vue
  src/components/projects/detail_ope/detail.vue
  src/components/projects/detail_ope/initialize.vue
  src/components/projects/env/env_detail/envConfig/home.vue
  src/components/projects/env/inner_env/envDetail.vue
  src/components/projects/env/inner_env/pmServiceDetail.vue
  src/components/projects/env/inner_env/serviceConfig.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/guide/common/runtime.vue
  src/components/projects/guide/helm/basicInfo.vue
  src/components/projects/guide/helm/delivery.vue
  src/components/projects/guide/helm/runtime.vue
  src/components/projects/guide/host/hostConfig.vue
  src/components/projects/guide/k8s/basicInfo.vue
  src/components/projects/guide/k8s/delivery.vue
  src/components/projects/guide/k8s/service.vue
  src/components/projects/guide/pm/config.vue
  src/components/projects/guide/pm/delivery.vue
  src/components/projects/guide/pm/deploy.vue
  src/components/projects/guide/pm/info.vue
  src/components/projects/policy/home.vue
  src/components/projects/rbac/member.vue
  src/components/projects/rbac/policy.vue
  src/components/projects/rbac/role.vue
  src/components/projects/serviceMgr/service.vue
  src/components/projects/test/common/function/function.vue
  src/components/projects/test/common/function/functionDetail.vue
  src/components/projects/test/function/functionSummary.vue
  src/components/projects/test/function/functionTaskDetail.vue
  src/components/projects/test/report/productWorkflowTestCase.vue
  src/components/projects/test/report/testCase.vue
  src/components/projects/workflow/commonTaskDetail.vue
  src/components/projects/workflow/list.vue
  src/components/projects/workflow/productDetail.vue
  src/components/projects/workflow/productTaskDetail.vue
Labels: enhancement

#709 feat: timing clean cache
  src/api/index.js
  src/components/setting/config/cache.vue
Labels: enhancement

#714 fix:using tailCut in env name.
  src/common/chromeTabs.vue
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#704 feat:release name support renaming.
  src/api/index.js
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/store/modules/serviceManage.js
Labels: enhancement

#705 feat: docker certificate
  src/components/setting/registry/manage.vue
Labels: enhancement

#716 feat:show host name and label in service detail.
  src/components/projects/env/inner_env/pmServiceDetail.vue
Labels: enhancement

#731 feat:add confirm dialog when saving release name.
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
Labels: enhancement

#732 feat:add confirm dialog when saving release name.
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
Labels: enhancement

#735 fix:get public key in created hook.
  src/components/entry/home.vue
Labels: bug

#747 fix:show addToEnvBtn when service is added.
  src/assets/css/component/service-editor.less
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#748 fix:show addToEnvBtn when service is added.
  src/assets/css/component/service-editor.less
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#752 fix:fix var undefined.
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug

#755 fix:change payload in pm env when updating.
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#756 fix:change payload in pm env when updating.
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#763 fix:fix redirect when adding service.
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
Labels: bug

#770 fix:fix error msg in distribteDeploy.
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
Labels: bug

#771 cherry-pick:#770
  src/components/projects/workflow/productTaskDetail.vue
  src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
Labels: bug

#772 fix:render variables when preview k8s yaml.
  src/components/projects/serviceMgr/common/importFromTemplate.vue
Labels: bug, enhancement

#774 feat:add doc link to custom account.
  src/components/profile/common/config.js
  src/components/setting/integration/account.vue
Labels: enhancement

#778 feat: sonar
  src/api/index.js
  src/components/setting/integration/components/sonarOperate.vue
  src/components/setting/integration/home.vue
  src/components/setting/integration/sonar.vue
Labels: enhancement

#777 feat:support update service when import from template.
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: enhancement

#779 fix:disable btn when vars is empty.
  src/components/projects/env/env_detail/components/updateK8sVarDialog.vue
Labels: bug

#715 feat: system role
  src/api/index.js
  src/components/projects/rbac/addRole.vue
  src/components/setting/users/components/roleOperate.vue
  src/components/setting/users/editUserInfo.vue
  src/components/setting/users/home.vue
  src/components/setting/users/manage.vue
  src/components/setting/users/role.vue
  src/router/index.js
Labels: enhancement

#783 fix: admin edit disabled
  src/components/setting/users/home.vue
  src/components/setting/users/role.vue
Labels: bug

#784 fix: defalut empty array
  src/components/projects/test/common/function/functionDetail.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
Labels: bug

#786 feat: default login account
  src/api/index.js
  src/components/setting/integration/account.vue
Labels: enhancement

#789 fix: push to unshift
  src/components/projects/test/common/function/container/advancedConfig.vue
  src/components/projects/test/common/function/functionDetail.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/notify.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/workflow.vue
Labels: enhancement

#796 fix: fix build template bugs.
  src/components/projects/build/commonBuild.vue
  src/components/projects/build/configDetail.vue
  src/components/projects/build/envVariable.vue
  src/components/templateLibrary/builds/envVariable.vue
Labels: bug

#795 fix role refresh and modify account tip
  src/components/setting/integration/account.vue
  src/components/setting/users/editUserInfo.vue
  src/components/setting/users/manage.vue
  src/components/setting/users/role.vue
Labels: bug

#797 fix:fix var is undefined in computed
  src/components/projects/build/configDetail.vue
Labels: bug

#798 fix: el-button to el-tag filter github
  src/components/setting/integration/account.vue
Labels: enhancement

#794 feat: suport multi jenkins
  src/api/index.js
  src/components/projects/build/commonBuild.vue
  src/components/projects/build/jenkinsBuild.vue
  src/components/setting/integration/jenkins.vue
Labels: enhancement

#799 fix:fix z-index in preview drawer.
  src/components/entry/home/topbar.vue
  src/components/templateLibrary/builds/otherSteps.vue
Labels: enhancement

#802 fix: api
  src/api/index.js
Labels: bug

#803 fix:fix style of user container.
  src/components/setting/users/components/roleOperate.vue
  src/components/setting/users/editUserInfo.vue
  src/components/setting/users/manage.vue
  src/components/setting/users/role.vue
Labels: bug

#804 fix(typo):fix typo of vars
  src/components/projects/build/envVariable.vue
  src/components/templateLibrary/builds/envVariable.vue
Labels: bug

#791 feat:enable share env in helm.
  src/components/projects/env/createEnv.vue
  src/components/projects/env/env_detail/components/manageHelmServicesDialog.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
Labels: enhancement

#805 fix:fix typo of var.
  src/components/projects/build/envVariable.vue
  src/components/templateLibrary/builds/envVariable.vue
Labels: bug

#806 fix(style):fix style of serviceRepoSelect comp.
  src/common/serviceRepoSelect.vue
Labels: bug

#808 fix:fix envList when adding service to helm.
  src/components/projects/serviceMgr/helm/components/common/updateHelmEnv.vue
Labels: bug

#807 fix(API):fix API route.
  src/api/index.js
Labels: bug
