Repository koderover/zadig-portal, pull requests merged in 2022-09, with the labels that each got.

#1189 feat:optimize template variable configuration.
  src/api/index.js
  src/components/projects/serviceMgr/common/importFromTemplate.vue
  src/components/templateLibrary/k8s/fileAside.vue
  src/components/templateLibrary/k8s/fileEditor.vue
  src/components/templateLibrary/k8s/fileTree.vue
  src/components/templateLibrary/k8s/index.vue
Labels: enhancement

#1194 fix:optimize permission-related ui issues.
  src/components/delivery/version/index.vue
  src/components/delivery/version/k8s/detail.vue
  src/components/projects/env/env_detail/envConfig/commonConfig.vue
  src/components/projects/env/env_detail/envConfig/versionHistory.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/hostEnv/createHostEnv.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/scanner/common/scannerRow.vue
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/components/projects/serviceMgr/k8s/container/policy.vue
  src/components/projects/workflow/list/virtualListItem.vue
Labels: bug

#1195 feat:add breadcrumb navigator to helm editor.
  src/components/projects/serviceMgr/helm/code.vue
  src/components/projects/serviceMgr/helm/components/editor/codeMirror.vue
Labels: enhancement

#1201 fix:fix provider type in host management.
  src/common/host/manageHost.vue
Labels: bug

#1205 fix(typo):fix typo of deletion.
  src/components/setting/registry/manage.vue
Labels: bug

#1206 fix(style):remove margin in el-alert__description
  src/assets/css/common/common.less
  src/assets/css/theme/index.css
Labels: bug

#1204 feat:supports editing vaules.yaml.
  src/api/index.js
  src/assets/css/component/service-mgr.less
  src/components/projects/serviceMgr/helm/code.vue
  src/components/projects/serviceMgr/helm/components/editor/codeMirror.vue
  src/components/projects/serviceMgr/helm/components/editor/folder.vue
  src/components/projects/serviceMgr/helm/components/helm/aside.vue
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
  src/store/modules/serviceManage.js
Labels: enhancement

#1208 fix:fix tab changing bug in helm editor.
  src/components/projects/serviceMgr/helm/code.vue
  src/store/modules/serviceManage.js
Labels: bug

#1211 fix:support for service updates via ops workflows.
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/env_detail/runWorkflow.vue
  src/components/projects/workflow/common/k8sArtifactDeploy.vue
  src/components/projects/workflow/common/pmArtifactDeploy.vue
  src/components/projects/workflow/common/runWorkflow.vue
Labels: bug, enhancement

#1215 chore:bump version of vue-ace2-bind.
  package.json
  yarn.lock
Labels: enhancement

#1214 fix:fix button issues caused by test links.
  src/components/projects/test/common/function/functionDetail.vue
  src/components/projects/test/function/functionSummary.vue
  src/components/projects/test/function/functionTaskDetail.vue
  src/components/projects/test/report/testCase.vue
  src/router/index.js
Labels: bug

#1209 fix(ui):fix several user experience issues
  src/assets/css/component/service-mgr.less
  src/components/projects/guide/helm/service.vue
  src/components/projects/guide/k8s/service.vue
  src/components/projects/serviceMgr/k8s/container/policy.vue
  src/components/projects/serviceMgr/k8s/serviceAside.vue
  src/components/projects/serviceMgr/serviceHost.vue
  src/components/projects/serviceMgr/serviceK8s.vue
  src/components/projects/workflow/productTaskDetail/artifactDeploy.vue
  src/components/projects/workflow/productTaskDetail/build.vue
  src/components/projects/workflow/productTaskDetail/deploy.vue
  src/components/projects/workflow/productTaskDetail/distributeDeploy.vue
  src/components/templateLibrary/builds/zadigBuild.vue
Labels: bug, enhancement

#1218 feat:upgrade service supports regular filtering branches.
  src/components/projects/env/env_detail/runWorkflow.vue
Labels: enhancement

#1220 fix:fix the bug that the build can't be saved.
  src/components/projects/build/advancedConfig.vue
  src/components/templateLibrary/builds/advancedConfig.vue
Labels: bug

#1221 chore:clean code and trim space.
  package.json
  src/components/common/workflowTestRows.vue
  src/components/entry/login.vue
  src/components/entry/passwordLogin.vue
  yarn.lock
Labels: enhancement

#1222 feat(style):optimize announcement management style.
  src/components/setting/announcement/manage.vue
  src/router/index.js
Labels: enhancement

#1223 feat: insert stage
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobCanaryDeploy.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobK8sDeploy.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: enhancement

#1226 fix(webhook):fix webhook data not changed.
  src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
Labels: bug

#1229 fix(webhook):using cloned data to listen changed.
  src/components/projects/workflow/workflowEditor/customWorkflow/components/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/webhookRunConfig.vue
Labels: bug

#1236 feat:support for displaying container logs on mobile.
  src/mobile/project/env/common/mobileContainerLog.vue
  src/mobile/project/env/helmServiceDetail.vue
  src/mobile/project/env/k8sServiceDetail.vue
Labels: enhancement

#1237 fix:fix gitlab branch search not working.
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
Labels: bug

#1241 chore:add docker file label.
  amd64.Dockerfile
Labels: enhancement

#1238 fix: set default service when only one service
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/mobile/project/workflow/product/common/runCustomWorkflow.vue
Labels: bug

#1250 fix(gitee):fix editor is editable when the source is gitee.
  src/components/projects/serviceMgr/k8s/serviceEditor.vue
Labels: bug

#1248 feat:add timer to trigger configuration.
  src/api/index.js
  src/components/common/customWorkflowBuildRows.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhook.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookGit.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookTimer.vue
Labels: enhancement

#1251 fix:fix web manifest icon path.
  static/site.webmanifest
Labels: bug

#1252 fix(webhook):get repo data through other API.
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
Labels: bug

#1256 fix:check the build name before getting the repo.
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
Labels: bug

#1257 fix:remove URL validation to support custom domains.
  src/components/projects/common/integrationRegistry.vue
  src/components/projects/serviceMgr/common/integrationCode.vue
  src/components/projects/serviceMgr/common/serviceTree.vue
  src/components/projects/serviceMgr/helm/components/common/gitRepo.vue
  src/components/setting/integration/code.vue
  src/components/setting/integration/components/sonarOperate.vue
  src/components/setting/integration/jira.vue
  src/components/setting/integration/other.vue
  src/components/setting/registry/manage.vue
Labels: bug

#1261 fix:limit the length of service names on mobile.
  src/mobile/project/test/runWorkflow.vue
  src/mobile/project/workflow/product/runWorkflow.vue
Labels: enhancement

#1263 feat:remove production environment permission checking.
  src/components/delivery/version/container/runWorkflow.vue
  src/components/entry/home/subTopbar.vue
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/components/serviceList.vue
  src/components/projects/env/env_detail/envConfig/commonConfig.vue
  src/components/projects/env/env_detail/envConfig/versionHistory.vue
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/env/helmEnv/createHelmEnv.vue
  src/components/projects/env/hostEnv/createHostEnv.vue
  src/components/projects/env/inner_env/serviceDetail.vue
  src/components/projects/env/k8sPmEnv/createK8sEnv.vue
  src/components/projects/serviceMgr/servicePm.vue
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/common/runWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/trigger.vue
  src/components/setting/cluster/manage.vue
  src/mobile/project/env/envDetail.vue
  src/mobile/project/workflow/product/common/runCustomWorkflow.vue
  src/mobile/project/workflow/product/runWorkflow.vue
  src/utilities/checkPermission.js
  src/utilities/defaultPermissions.js
  src/utilities/utilities.js
Labels: enhancement
