Repository koderover/zadig-portal, pull requests merged in 2023-03, with the labels that each got.

#1687 fix: default image selection error
  src/components/projects/env/k8sPmEnv/k8sServiceList.vue
Labels: bug

#1688 fix: helm service style error
  src/components/projects/serviceMgr/helm/code.vue
Labels: bug

#1691 feat:show status in dashboard.
  src/assets/css/quote/iconfont.css
  src/assets/fonts/iconfont/iconfont.eot
  src/assets/fonts/iconfont/iconfont.ttf
  src/assets/fonts/iconfont/iconfont.woff
  src/assets/fonts/iconfont/iconfont.woff2
  src/assets/icons/font/iconfont.svg
  src/components/dashboard/dashboard.vue
  src/components/dashboard/index.vue
  src/components/dashboard/status/container/customWorkflowStatus.vue
  src/components/dashboard/status/container/productWorkflowStatus.vue
  src/components/dashboard/status/container/scannerStatus.vue
  src/components/dashboard/status/container/testStatus.vue
  src/components/dashboard/status/status.vue
  src/components/entry/home/sidebar.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/router/index.js
Labels: enhancement

#1692 feat:show recent task charts in the workflow list.
  package.json
  src/components/projects/workflow/common/statusBarChart.vue
  src/components/projects/workflow/list/workflowRow.vue
  yarn.lock
Labels: enhancement

#1693 feat:optimize jenkins validation behavior.
  src/api/index.js
  src/components/setting/integration/components/addJenkins.vue
Labels: enhancement

#1694 feat:optimize sonar validation behavior.
  src/components/setting/integration/components/sonarOperate.vue
Labels: enhancement

#1695 feat:optimize project management validation behavior.
  src/api/index.js
  src/components/setting/integration/project.vue
Labels: bug

#1696 fix:fix permission lacking style of env change log.
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: bug

#1701 fix: minor bugs
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/productCustomTaskDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobBuildDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobScanningDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobTestDetail.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/canInput.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/stage.vue
Labels: bug

#1705 feat: ns and services are not deleted by default
  src/components/projects/detail_ope/components/deleteProject.vue
  src/components/projects/env/env_detail/envDetailComp.vue
Labels: enhancement

#1707 docs: modify description
  src/components/projects/env/env_detail/components/chartList.vue
  src/components/projects/env/env_detail/components/serviceList.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: documentation

#1706 feat: support for hidden repos
  src/common/repoSelect.vue
  src/common/serviceRepoSelect.vue
  src/components/common/customWorkflowBuildRows.vue
  src/components/common/customWorkflowCommonRows.vue
  src/components/common/workflowBuildRows.vue
  src/components/common/workflowTestRows.vue
  src/components/projects/scanner/common/runScannerTask.vue
  src/components/projects/scanner/create.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/container/workflowArgs.vue
  src/mobile/project/workflow/product/common/workflowBuildRows.vue
  src/mobile/project/workflow/product/common/workflowTestRows.vue
Labels: enhancement

#1710 feat:optimize the progress display of environment creation.
  src/components/projects/guide/helm/runtime.vue
  src/components/projects/guide/k8s/runtime.vue
Labels: enhancement

#1711 chore:chore:clean code.
  src/components/projects/workflow/list/virtualListItem.vue
  src/components/projects/workflow/list/workflowRow.vue
Labels: enhancement

#1712 feat:show more data in job container.
  src/components/projects/workflow/productCustomTaskDetail.vue
Labels: enhancement

#1715 feat: optimize action
  src/assets/css/component/env-detail.less
  src/components/projects/env/env_detail/envDetailComp.vue
  src/components/projects/workflow/list.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobDeploy.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/jobs/jobK8sDeploy.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/store/index.js
  src/store/modules/workflowTabs.js
  src/store/mutations.js
Labels: enhancement

#1720 feat: add built-in test variables
  src/components/projects/build/envVariable.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/config.js
  src/components/templateLibrary/builds/envVariable.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: enhancement

#1719 feat: custom workflow config scroll
  src/components/projects/workflow/productCustomTaskDetail.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: enhancement

#1718 fix:get images by image_name.
  src/components/projects/workflow/common/runCustomWorkflow.vue
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/webhookRunConfig.vue
  src/mobile/project/workflow/product/common/runCustomWorkflow.vue
Labels: bug

#1722 fix: css
  src/components/projects/workflow/workflowEditor/customWorkflow/index.vue
Labels: bug

#1723 feat:using latest build config when run custome workflow.
  src/components/projects/workflow/common/runCustomWorkflow.vue
Labels: enhancement
