Repository koderover/zadig-portal, pull requests merged in 2023-05, with the labels that each got.

#1739 fix:add authorization to system integration.
  src/router/index.js
Labels: bug

#1738 feat: optimize action
  .vscode/settings.json
  patches/element-ui+2.15.10.patch
  src/components/setting/cluster/manage.vue
Labels: enhancement

#1742 fix:fix prop typo.
  src/components/projects/workflow/productCustomTaskDetail.vue
  src/components/projects/workflow/productCustomTaskDetail/jobFreestyleDetail.vue
Labels: bug

#1740 fix: notify all members
  src/components/projects/workflow/workflowEditor/customWorkflow/components/base/notifyOperate.vue
  src/components/projects/workflow/workflowEditor/productWorkflow/modules/components/notifyItem.vue
  src/lang/en.js
  src/lang/zh-CN.js
Labels: bug

#1743 feat:support retry custom workflow task.
  src/api/index.js
  src/components/projects/env/envDetail/components/chartList.vue
  src/components/projects/workflow/customWorkflowDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobBuildDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobDeployDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobFreestyleDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobImageDistributeDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobK8sDeployDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobK8sResourceUpdateDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobPluginDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobScanningDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/jobTestDetail.vue
  src/components/projects/workflow/customWorkflowTaskDetail/stageApproval.vue
  src/components/projects/workflow/productWorkflowDetail.vue
  src/components/projects/workflow/productWorkflowTaskDetail.vue
  src/components/projects/workflow/productWorkflowTaskDetail/artifactDeploy.vue
  src/components/projects/workflow/productWorkflowTaskDetail/build.vue
  src/components/projects/workflow/productWorkflowTaskDetail/deploy.vue
  src/components/projects/workflow/productWorkflowTaskDetail/distributeDeploy.vue
  src/components/projects/workflow/productWorkflowTaskDetail/extension.vue
  src/components/projects/workflow/productWorkflowTaskDetail/filterStatus.vue
  src/components/projects/workflow/productWorkflowTaskDetail/test.vue
  src/lang/en.js
  src/lang/zh-CN.js
  src/router/index.js
Labels: enhancement

#1741 feat:optimize the Insight experience.
  src/api/index.js
  src/components/insight/common/subTopbar.vue
  src/components/insight/home.vue
  src/components/insight/test/averageDuration.vue
  src/components/insight/test/deploy.vue
  src/components/insight/test/health.vue
  src/components/insight/test/trend.vue
  src/components/projects/build/zadigBuild.vue
  src/router/index.js
Labels: enhancement

#1744 fix(typo):fix typo of project list.
  src/lang/zh-CN.js
Labels: typo

#1746 fix:remove the min-width limit of the k8s yml pane to make dragging more flexible.
  src/assets/css/component/service-mgr.less
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: enhancement

#1747 fix:add initial values to avoid the container being propped up.
  src/assets/css/component/service-mgr.less
  src/components/projects/serviceMgr/serviceK8s.vue
Labels: bug
